### ISSUE TITLE
Upload page to Web Server

### ISSUE THREAD

**Issue by RyChrome** [UB-CSE/course-project-a3-thinkofagoodname#22]
Task Test: 
1. Open a web browser
2. Type 69.164.218.217 into the web address bar
3. Repeat steps 1 and 2 on a different computer/internet connection to show the website is accessible to everyone

Task Test: 
1. Open a web browser
2. Type 69.164.218.217/taskTest into the web address bar (or any address that does not exist on the website)
3. Check that the response is "**Not Found** The requested resource is not found on this server." to ensure the app was deployed with DEBUG mode turned off

Task Test: 
1. Open a web browser
2. Type 69.164.218.217/download into the web address bar (or any address that exists on the website)
3. Check that the response is the correct corresponding webpage

**Comment by katsemenova** [comment]
User story dependancy? task tests?
