### ISSUE TITLE
As a producer using openbeats to create a song, I want to be able to bind instruments to my computer key board, so that I can easily create songs

### ISSUE THREAD

**Issue by Nicholas-A-Smith** [UB-CSE/course-project-a3-thinkofagoodname#3]
Acceptance Test
1. A producer uses openbeats to set the keys on their keyboard to the sound of their choosing
2. A producer presses a key they have setup
3. Openbeats will play the sound paired with that key

**Comment by katsemenova** [comment]
Reword user story so it reflects that you are building the UI for it. "As a producer using openbeats to create a song, I want to be able to have a way to bind instruments to my computer key board, so that I can create songs"
