### ISSUE TITLE
Link homepage buttons to their corresponding pages 

### ISSUE THREAD

**Issue by jmccart16** [UB-CSE/course-project-a3-thinkofagoodname#41]
1. Navigate to Open Beats home page. 
2. See "Sharing" "Shared" "Editor" "Download" "Project" buttons under the page title
3. Clicking the "Sharing" button will bring you to the page for sharing songs with other artists
4. Clicking the "Shared" button will bring you to the page to open projects shared with you by other artists 
5. Clicking the "Editor" button will bring you to the page to open and edit one of your musical projects 
6. Clicking the "Download" button will bring you to the page to download any of your musical projects  
7. Clicking the "Project" button will bring you to the page with info about open beats

**Comment by katsemenova** [comment]
task tests?
