### ISSUE TITLE
Add basic instrument sounds for key binding in editor page 

### ISSUE THREAD

**Issue by jmccart16** [UB-CSE/course-project-a3-thinkofagoodname#50]
1. Navigate to the Open Beats editor page
2. Look under the song selection buttons
3. See "Synth" "Oscillator type"  labels
4. Click a synth type below the "Synth" label
5. Select an oscillator type below the "Oscillator type" label
6. See that selected sounds play when bound keys are pressed

**Comment by katsemenova** [comment]
Add the correct user story to this
